"""empty message

Revision ID: 2e9bea35f698
Revises: 
Create Date: 2024-12-03 12:48:43.143371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9bea35f698'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_queue', 'run', 'completed', name='status'), nullable=False),
    sa.Column('create_time', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('exec_time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
